version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      # makes the UI portable across environments
      - NEXT_PUBLIC_API_URL=http://localhost:8000